In [ ]:
# 1 Create:4x4 matrix of ones
import numpy as np
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# 2. create Array from 5 to 25 with step 5
np.arange(5,25,5)

array([ 5, 25,  5])

In [ ]:
# 3. create 5 evenly spaced numbers between 0 and 10
np.linspace(0,10,5)

In [ ]:
''' 4 .Create:

[[10,20,30],
 [40,50,60],
 [70,80,90]]

Print:

shape

ndim

size

dtype
'''

In [ ]:
n =np.arange(10,100,10)
n

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
ex=n.reshape(3,3)
ex

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
#shape
ex.shape



(3, 3)

In [ ]:
#ndim
ex.ndim

2

In [ ]:
#size
ex.size

9

In [ ]:
#dtype
ex.dtype

dtype('int64')

In [ ]:
#5
'''a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

Get:

First row

Last column

Middle element

First two rows'''

In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[1,:]

array([4, 5, 6])

In [ ]:
a[:,2]

array([3, 6, 9])

In [ ]:
a[:,1]

array([2, 5, 8])

In [ ]:
a[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 6Create an array from 1 to 20.
import numpy
import numpy as np
n =np.arange(1,21)
print(n)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#7 Create a 5x5 matrix filled with zeros.
import numpy
np.zeros((5,5))

array([0., 0., 0., 0., 0.])

In [ ]:
#8 Create a 4x4 identity matrix.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#9 created numpy array with numpy array module with data type int and float
import numpy as np
x =np.array([1,2,34,5])
print(x)
print(x.dtype)


[ 1  2 34  5]
int64


In [ ]:
import numpy as np
y =np.array([1.1,2.2,3.4])
print(y)
print(y.dtype)

[1.1 2.2 3.4]
float64


In [ ]:
#10 numpy array of zeroes,one,two,three dimension array respectfully.
#and also print there shape and dimension of the numpy array created
#1d array
import numpy as np
new=np.array((3,3))
print(new)
print(new.shape)
print(new.dtype)
print(new.ndim)

[3 3]
(2,)
int64
1


In [ ]:
import numpy as np
n=np.ones((4,3))
print(n)
print(n.shape)
print(n.dtype)
print(n.ndim)
#or  you can also created 2 dim
i =np.array([[1,3,4],
            [4,5,6]])
print(i)
print(i.ndim)




[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(4, 3)
float64
2
[[1 3 4]
 [4 5 6]]
2


In [ ]:
three =np.array([[[1,2,3],
                  [2,3,4]]])
print(three)


[[[1 2 3]
  [2 3 4]]]


In [ ]:
w=np.array([[[4,3],
           [7,8]]])
print(w)
print(w.shape)
print(w.ndim)

[[[4 3]
  [7 8]]]
(1, 2, 2)
3


In [ ]:
#0 dimnesion
n =np.array(34)
print(n)

34


In [ ]:
#11 created 1*1 2*2 3*3 identity matrix
import numpy as np
q=np.eye(1)
print(q)
print(q.shape)
print(q.ndim)

[[1.]]
(1, 1)
2


In [ ]:
p=np.eye(2)
print(p)

[[1. 0.]
 [0. 1.]]


In [ ]:
r=np.eye(3)
print(r)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#12 creat numpy array with 2*5 dimension having everything ones init
import numpy as np
arr =np.zeros((2,5))
print(arr)
#or
print(np.full((2,5),0))


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
