In [5]:
#create numpy randam integer with range(1,100)
import numpy as np
v=np.random.randint(1,100,size=25)
print(v)

[46  9 76  5 41 51 85 11 49 28 24 24 23 45 63 16 72 56 75 47 91 99 92  3
 48]


In [12]:
#create an array(2*3) with random integer  reshape the above array(3*2)
arr=np.random.randint(1,101,size=(2,3))
print(arr)
print(arr.reshape(3,2))

[[67 27 82]
 [98 17  5]]
[[67 27]
 [82 98]
 [17  5]]


In [16]:
#create a array contains 7 number with evenely spaced 5 number
import numpy as np

print(np.linspace(-5,5,5))

[-5.  -2.5  0.   2.5  5. ]


In [18]:
#create 2D array of shape(2*3) get random array of floating number
import numpy as np
arr=np.random.random([2,3])
print(arr)

[[0.73090253 0.51838315 0.52180506]
 [0.04421039 0.00717623 0.76281925]]


In [24]:
#Genrate the random floating number between 5,10 of size (2*3)
import numpy as np
arr = np.random.uniform(5,10,size=(2,3))
print(arr)

[[7.42003466 7.04946747 9.86616845]
 [6.55087967 6.04482422 5.12980648]]


In [30]:
#create numpy array of int 10 to 50 and extract all the even number
import numpy as np
arr=np.arange(10,51)
print(arr)
#x=[i for i in arr if i%2==0] #Thise is the advantage of array without using for
#print(x)
p=arr[arr%2==0]
print(p)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
'''
create randam array with the range(0,100000) with the size 50
a. print the first 10 ,last 10 elements
b.print the elements from index 10 - 25
c.print the elements at the index 25
d.print the elements using negtive index
e.print the last 10 elements using negetive indexing
'''


In [32]:
import numpy as np
arr =np.random.randint(0,100,size=50)
print(arr)

[55 11 85 88 96 81 86 38 89  1 99 23 41 45 45 97 97 94 36 60  5 63 55 85
 84 59 51 29 79 34 22 97 51 10 24 69 57 81 12 14 49 58 43 30 32 69 76  9
 86 55]


In [33]:
print(arr[:10])

[55 11 85 88 96 81 86 38 89  1]


In [42]:
print(arr[40:])

[49 58 43 30 32 69 76  9 86 55]


In [41]:
print(arr[10:26])

[99 23 41 45 45 97 97 94 36 60  5 63 55 85 84 59]


In [35]:
print(arr[22])

55


In [43]:
print(arr[-51:])

[55 11 85 88 96 81 86 38 89  1 99 23 41 45 45 97 97 94 36 60  5 63 55 85
 84 59 51 29 79 34 22 97 51 10 24 69 57 81 12 14 49 58 43 30 32 69 76  9
 86 55]


In [40]:
print(arr[-10:])

[49 58 43 30 32 69 76  9 86 55]


In [ ]:
'''
#Given numpy arra[1,2,3,4,5]
a.Insert element 10 at end
b.20 at bigginig
c.30 before 4
d. delete 30
e.soting in ascending '''

In [44]:
new=np.array([1,2,3,4,5])
print(new)

[1 2 3 4 5]


In [45]:
print(np.append(new,6))

[1 2 3 4 5 6]


In [47]:
print(np.insert(new,0,9))


[9 1 2 3 4 5]


In [50]:
p=(np.insert(new,4,30))
print(p)

[ 1  2  3  4 30  5]


In [52]:
print(np.delete(new,3))


[1 2 3 5]


In [53]:
print(np.sort(new))

[1 2 3 4 5]
