In [ ]:
import numpy as np

1) For a given numpy array, how will you change the dimensions to 5 using the existing parameters in the numpy array. my_array = numpy.array([[[[1,3,4]]]])

2.Given a NumPy array , arr=np.array( [ [6,9,12] , [8,3,7] , [9,8,0] ] ) Find the correct command from the following options to get an output array as [27 18 17]?

In [ ]:
arr=np.array( [ [6,9,12] , [8,3,7] , [9,8,0] ] )
print(np.sum(arr,axis=1))

[27 18 17]


3.Create a sequence number from 13 to 22 and increment by 4 .What is the index element 17?

In [ ]:
arr1=np.arange(13,22,4)
x=[x for x in range(len(arr1)) if arr1[x]==17]
print("Element 17 at index  is:",x)

Element 17 at index  is: [1]


In [ ]:
#4.The output of the code given below is:
List =[3,9,12,15]
a=(x**3 for x in List)
print(next(a)) #next will give values always from start
print(next(a))

5.The command to find the number of elements in the following array
“N” is

In [18]:
N=np.array([ 99 , None , 49 , np.nan , 63 , 50])
print(N.size)

6


In [20]:
#5
arr1 = np.array([[3,2,1],
                 [6,4,5],
                 [8,7,9]])
col_max=np.max(arr1,axis=0)
row_min=np.min(arr1,axis=1)
print("Reslut =",col_max-row_min)

Reslut = [7 3 2]


#6Create a nested numpy array from a given dictionary data.
sample = {1: [1,2],
2: [[1],[2]],
3: [[1,2], [3,4], [4,5]],
4: [1],
5: [1,2,3,4,5]}

In [32]:
sample = {1: [1,2], 2: [[1],[2]], 3: [[1,2], [3,4], [4,5]], 4: [1], 5: [1,2,3,4,5]}
values=list(sample.values())
A=np.array(values, dtype=object)
print(A)

[list([1, 2]) list([[1], [2]]) list([[1, 2], [3, 4], [4, 5]]) list([1])
 list([1, 2, 3, 4, 5])]


# 7Given two vectors A and B, find the correlation coefficient of the following vectors.

In [35]:
A = np.array([1,3,5,7,9,11,13,15,17,19,21,23,25])
B = np.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])
print(np.corrcoef(A,B))

[[1. 1.]
 [1. 1.]]


8.Given two vectors A and B, find the cross product between the two

In [37]:
A = np.array([4, 12, 29])
B = np.array([13, 21, 4])
print(np.cross(A,B))

[-561  361  -72]


# 9.For the given arrays, array1 and array2, if we stack the two arrays column wise, what will
be the output?

In [38]:
#When we stack arrays column-wise, we are placing one array as a new column next to another array.
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
print(np.column_stack((array1, array2)))

[[1 2 5 6]
 [3 4 7 8]]


10.For the given numpy arrays, Array1 and Array2, what will be the dot product for the

In [ ]:
Array1 = array([[1, 2, 3], [4, 5, 6]])
Array2 = array([[2, 3],[3, 2]])  #ValueError: shapes (2,3) and (2,2) not aligned